name: Build Python Image with Packer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  packer_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install HashiCorp Packer
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update && sudo apt-get install packer

    - name: Build Docker image
      run: |
        packer build python_image.pkr.hcl | tee output.log
        export IMAGE_ID=$(cat output.log | grep 'docker' | awk '{print $NF}')
        IMAGE_ID=$(echo "$IMAGE_ID" | tail -n 1)

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create ECR repository
      run: |
        aws ecr create-repository --repository-name my-repo --image-scanning-configuration scanOnPush=true

    - name: Set image tag
      id: set_tag
      run: echo "::set-output name=tag::latest"

    - name: Tag Docker image
      run: |
        docker tag python:latest ${{ secrets.AWS_REGISTRY_URL }}/my-repo:${{ steps.set_tag.outputs.tag }}
    - name: Push Docker image to AWS ECR
      run: |
        docker push ${{ secrets.AWS_REGISTRY_URL }}/my-repo:${{ steps.set_tag.outputs.tag }}

      env:
        AWS_REGISTRY_URL: ${{ secrets.AWS_REGISTRY_URL }}
